### ISSUE TITLE
Feature request: Disable screen shutoff while recording video

### ISSUE THREAD

**Issue by scottlinux** [PkmX/lcamera#120]
When recording a video, the screen turns off as if the device is idle. Video then stops recording.

Is it possible to disable the screen timeout / poweroff when recording a video?

**Comment by PkmX** [comment]
Which version are you running on your device? v0.3 should already keep the screen on as long as the app is running.

**Comment by scottlinux** [comment]
I can no longer reproduce this. Ok to close thanks,
