### ISSUE TITLE
Preview has a cropped image

### ISSUE THREAD

**Issue by huusman** [PkmX/lcamera#126]
Since build v0.3 the preview for both photo and video mode is cropped. The image is only cropped when previewing in the app, I'd say it's cropped 80% on the sensor from the center. When viewing the pictures afterwards the crop is gone and photo's have the same dimensions etc. as the google camera app.

**Comment by kagwind** [comment]
Confirm this problem.
The same happened to the google camera, but they finally  changed it.

**Comment by ZambettiAle** [comment]
Same problem on nexus 5

**Comment by Srandista** [comment]
I did some testing, and only in version 0.1 the preview on display is actually, what you get on photo. In all following version is preview on display different from result captured by camera.

**Comment by kagwind** [comment]
Thanks Srandista. I may look into the code based on what you tested.

**Comment by Srandista** [comment]
I did comparison through all versions of lcamera, and for reference also for Google Camera. Captured image go first, then comes screenshot of screen in time of shooting. 

Order of pictures: lcamera version 0.1, 0.2, 0.3, dev and Google Camera. 

![lcamera_1](https://cloud.githubusercontent.com/assets/5399824/6355172/4f99bf06-bc54-11e4-9867-53d01253ad85.jpg)
![lcamera_1_screenshot](https://cloud.githubusercontent.com/assets/5399824/6355175/4f9cb936-bc54-11e4-8dd8-129052b13bd3.jpg)
![lcamera_2](https://cloud.githubusercontent.com/assets/5399824/6355173/4f99d630-bc54-11e4-9a44-feb13847e787.jpg)
![lcamera_2_screenshot](https://cloud.githubusercontent.com/assets/5399824/6355176/4f9df166-bc54-11e4-91dd-010047c039d5.jpg)
![lcamera_3](https://cloud.githubusercontent.com/assets/5399824/6355180/50151868-bc54-11e4-8cf8-a59f565b90b8.jpg)
![lcamera_3_screenshot](https://cloud.githubusercontent.com/assets/5399824/6355178/4fb3c9a0-bc54-11e4-8ea3-9d2c08e28dd1.jpg)
![lcamera_dev](https://cloud.githubusercontent.com/assets/5399824/6355177/4fb1b732-bc54-11e4-98be-55e611cb8a6e.jpg)
![lcamera_dev_screenshot](https://cloud.githubusercontent.com/assets/5399824/6355179/4fb6143a-bc54-11e4-8829-aeb0d3d7d87d.jpg)
![google_camera](https://cloud.githubusercontent.com/assets/5399824/6355171/4f912d00-bc54-11e4-827b-2b73e8f82852.jpg)
![google_camera_screenshot](https://cloud.githubusercontent.com/assets/5399824/6355174/4f9c2f7a-bc54-11e4-86db-0fbe787412f6.jpg)

**Comment by PkmX** [comment]
Fixed in the latest dev-build release.
