### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by Slobo2712** [PkmX/lcamera#134]
I see that latest released verion is on Nov 25, 2014.So there will not be any new verions anymore or i'm missing something?Tnx

**Comment by Fishywalrus** [comment]
Also wondering if this project has come to a standstill.. such potential already!

**Comment by sharathdaniel** [comment]
I'm also waiting for an update.

**Comment by Msamii** [comment]
It didn't stop you guys. Can't you see the most recent commit. It's done 4 days ago. Have patience

**Comment by vishesh29** [comment]
Haha. Sorry! Well you've made something we all cherish! It's really very
hard to wait.

PS - Thank You.

**Comment by Msamii** [comment]
Haha well I didn't made it. All goes to the awesome man who did it "@PkmX"

**Comment by vishesh29** [comment]
I know. Lol. I really wish slow motion for Nexus 6 comes in the upcoming
release.

**Comment by Msamii** [comment]
Let's hope the best and congrats you've got Nexus 6 :') I got 5
