### ISSUE TITLE
manual aperture/iris

### ISSUE THREAD

**Issue by goinghome1** [PkmX/lcamera#135]
Not sure if this is possible with the new api but would be an awesome feature.

**Comment by PkmX** [comment]
The API allows manual aperture control, but both Nexus 5/6's cameras have fixed aperture, so it's impossible for now.

**Comment by vishesh29** [comment]
I've been using lcamera on my Nexus 6 since you released v0.1 and it has
changed a lot! Will you be releasing an update soon? Cause we really need
one.
