### ISSUE TITLE
ISO lower than 100

### ISSUE THREAD

**Issue by Fishywalrus** [PkmX/lcamera#147]
Using the Nexus 5, you can choose ISO 40, 50 & 80 on build 0.3 and the noise levels in the DNGs do seem to change accordingly.. The latest dev build however seems to be limited to 100 and above..

**Comment by PkmX** [comment]
Do you have any samples images? IIRC, any ISO values below 100 is simply clamped back to 100 on the N5, and therefore have no effects.

**Comment by Fishywalrus** [comment]
After looking at the dngs, I apologise, you are correct, they all are at ISO100!
