### ISSUE TITLE
can i use L camera in kitkat for 60/ 120 fps

### ISSUE THREAD

**Issue by karthi1** [PkmX/lcamera#154]
i m reverting my nexus 5 to android 4.4.4 again. so will i b able to use this app in kitkat for recording 60/120 fps. if its possible in any way ????

**Comment by Virkkunen** [comment]
Impossible. As stated, this app requires the Camera API 2, that is only available on Lollipop.

**Comment by PkmX** [comment]
In theory, that is possible (the hack was originally developed on 4.4). However, you could only do it by hooking into various low-level qualcomm-specific API, so it is not going to be anywhere close to be user-friendly.
