### ISSUE TITLE
I lost libmmcamera_imx179.so :(

### ISSUE THREAD

**Issue by djustinW** [PkmX/lcamera#158]
I was playing around with the slow mo and then i wanted to put the original lib file back, but i moved it to the wrong folder and my system chrashed and i had an backup so i recovered it but i made the backup before the backup of "libmmcamera_imx179.so" .... So i lost it...
Can somebody link me a "libmmcamera_imx179.so"

**Comment by krusic22** [comment]
https://github.com/modbrin/libchanger/releases Try this. Just click stock and hope it works.
