### ISSUE TITLE
the option 60/120 fps is not working on lollipop 5.1.1 or 5.1

### ISSUE THREAD

**Issue by bultodepapas** [PkmX/lcamera#167]
hi, maybe is just me, but i try the option 60/120 fps on lollipop 5.1.1 or 5.1 and it is not working.

**Comment by Hiradur** [comment]
Did you replace the system library following the guide in the readme?

**Comment by bultodepapas** [comment]
Yes, I am on 5.1.1 nexus 5, I think that this is the problem

**Comment by dondaa1** [comment]
for me l camera doesnt load after I replaced the system library file

**Comment by PkmX** [comment]
Added patched 60fps `libmmcamera_imx179.so` library for Android 6.0, see release page.
