### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by gartha1** [PkmX/lcamera#191]
I have an upgraded Android.. Nexus 4, Android 4.4    And my phone is rooted.

I downloaded the apk

https://github.com/PkmX/lcamera/releases/download/dev-build/lcamera-debug.apk

But I get 

"Parse error.  There was a problem while parsing the package."

https://i.ytimg.com/vi/_oPsC4Q_94c/hqdefault.jpg

**Comment by PkmX** [comment]
First of all, LCamera requires Camera2 API to work which is only available on Lollipop (Android 5.0). Furthermore, Nexus 4 doesn't fully support the Camera2 API even on Lollipop, so I think you are out of luck here.
