### ISSUE TITLE
Quick Lib Changer

### ISSUE THREAD

**Issue by modbrin** [PkmX/lcamera#61]
Hello again, pkmx,
It takes some time to change 60hz lib to normal. So, i created a small app. This app uses two files in sdcard. And the lib can be changed very quickly. After changing, l camera have to be restarted.
![screenshot_2014-11-18-17-03-22](https://cloud.githubusercontent.com/assets/9750068/5087198/6ad7b124-6f47-11e4-839d-69d61aa6e7a4.png)
![screenshot_2014-11-18-17-27-21](https://cloud.githubusercontent.com/assets/9750068/5087264/49c720ae-6f48-11e4-98b9-989f355481a5.png)

**Comment by Wicked0ne** [comment]
I was bored today and decided to expand upon modbrin's lib changer to add some checks and stuff like that. This one ships with all 3 library files included into the apk(stock, 60fps, and 120fps). Feel free to check it out and use it in any way you want to. https://github.com/Wicked0ne/LCameraLibChanger

Side note: I have not written java or developed for Android in over a year. Please be gentle lol.

**Comment by DirtyDroidX** [comment]
I will test the beta version of the camera stock and use the lib changer to modify it on my N6. If I have any problems I will look through the code. Regardless, I will post back details of my tests.

**Comment by DirtyDroidX** [comment]
Edit, just seen its for N5. If stock don't work I will edit for shamu.

**Comment by Wicked0ne** [comment]
From my understanding(correct me if I'm wrong) the 60/120 fps mods are only for Nexus 5's. I hard coded a check into my app to check if its a Nexus 5 and wont do anything if it fails to find it's a Nexus 5
