### ISSUE TITLE
Missing Broadcast Event ACTION_NEW_PICTURE

### ISSUE THREAD

**Issue by 8h2a** [PkmX/lcamera#92]
It seems that this app doesn't broadcast the event ACTION_NEW_PICTURE when a picture is taken:
https://developer.android.com/reference/android/hardware/Camera.html#ACTION_NEW_PICTURE

So apps depending on this broadcast (like ownclouds InstaUpload) won't work.:
https://github.com/owncloud/android/issues/760

**Comment by thedd** [comment]
@PkmX Could you reopen this issue and respond to @tobiasKaminsky's post please?
